Numpie

.For faster operation

.list implementation is complex

.it is also known as vectors


In [ ]:
import numpy as np
# print(np.__version__)

np_arr=np.array([3,3,3,33.3,'hello',False])
print(bool(np_arr[-1]))
print(np_arr[-2])
a=False
print(bool(a))



a=np.zeros(3)
b=np.zeros((2,3))
c=np.zeros((2,3,4)) #avi data type float hai data type int ke liye dtype=int kardo

d=np.ones((2,3,4),dtype=int)
#ye array ke andar arrayke andar array jaisa hai


print(a)
print(b)
print(c)
print(d)
print(type(c[0][0][0]))
print(type(d[0][0][0]))




True
hello
False
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.float64'>
<class 'numpy.int64'>


In [ ]:
a=np.empty(4,dtype=int) #random values dega garbage se
print(a)

b=np.full((4,3),5,dtype=int) #zeroes ones me 1 ya 0 mil raha tha but yaha koi bhi values de sakte hai
print(b)

c=np.full(4,5,dtype=int) 
print(c)


d=np.arange(2,8,1,dtype=int) #start stop step dtype ek parameter diya to vo stop lega
print(d)

e=np.linspace(2,9,3,dtype=int) #start stop kitivalues cahiye and  dtype and endpoint false kar sakte hai by default true hai
print(e)



[5 5 5 5]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
[5 5 5 5]
[2 3 4 5 6 7]
[2 5 9]


In [73]:
a=np.full((3,3),3,dtype=int)
print(a)
print(np.size(a)) #no of elements
print(np.shape(a)) #row,column

c=np.random.randint(1,100,4) #start,stop,size
print(c)

d=np.random.choice(100,size=(3,4)) #int ,size
print(d)


[[3 3 3]
 [3 3 3]
 [3 3 3]]
9
(3, 3)
[96  9 47 38]
[[34 47 97 38]
 [24  7 70  9]
 [ 4 15 33 27]]


Broadcasting
array ke saare element pe operations perform hoga list me concat hoga

In [110]:
a=np.full((3,3),2,dtype=int) 
b=np.full((3,3),2,dtype=int)



print(a*2)
print(b*3)
print(a*b)
print(a//b)
print(a+b)

lst=np.random.randint(1,5,4)
lst1=np.random.randint(1,5)

print(lst*2)
print(lst+lst1)
print(lst*lst1)




[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[6 8 6 6]
[6 7 6 6]
[ 9 12  9  9]


In [4]:
import numpy as np
a=np.random.randint(1,4,6)
print(a)
b=a.reshape((2,3)) # lst ke  dimension change karega
# print(b)
c=a.reshape((3,2))
# print(c)

d=b.transpose()
# print(d)

e=b.reshape(2,3)
# print(e)

f=np.concatenate((b,e))
# print(f)


g=np.random.randint(1,4,6)
print(g)
h=np.concatenate((a,g))
print(h)






[1 2 1 1 3 3]
[3 2 2 2 1 1]
[1 2 1 1 3 3 3 2 2 2 1 1]


where function 

In [156]:
#where fucntion
a=np.random.randint(2,15,6)
print(a)
b=np.random.randint(1,10,6)
print(b)


wh=np.where(b>2,b,a) #where(condiotion,x,y) true hoga condn to x ni to y value b>2 har ek element greater than 2 tab b milega wh me ni to a
# print(wh)
srt=np.sort(b)
print(srt)

sumi=np.sum(a)
print(sumi)

mn=np.mean(a)
print(mn)

mini=np.min(a)
print(mini)

maxi=np.max(a)
print(maxi)

unq=np.unique(a)
print(unq)

c=np.random.randint(0,10,(3,3))
d=np.random.randint(0,10,(3,3))

e=np.matmul(c,d)
print(e)




[13  5 10  7 10  5]
[4 1 1 5 8 5]
[1 1 4 5 5 8]
50
8.333333333333334
5
13
[ 5  7 10 13]
[[ 26 138  46]
 [ 24  73  57]
 [ 36  99  87]]


In [ ]:
days=int(input())


# for i in range(0,days):
#     score=int(input())

#     lst.append(score)



scores=input().split()
print(scores)

scores=[int(x) for x in scores]

arr=np.array(lst)
day=np.array(["Monday" , "Tuesday" ,"Wednesday" ,"Thrusday" ,"Friday","saturday" ,"sunday"])

for i in range(0,days):
    print(f"{day[i]} performance is :",arr[i])

sumi=np.sum(arr)
print("sum is :",sumi)

mn=np.mean(arr)
print("mean is:", mn)

mini=np.min(arr)
print("min performance is :",mini)

maxi=np.max(arr)
print("max prformance is :",maxi)




['10', '20', '30']
Monday performance is : 10
Tuesday performance is : 20
Wednesday performance is : 30
sum is : 280
mean is: 40.0
min performance is : 10
max prformance is : 70
