In [28]:
import numpy as np
array=np.random.randint(1,91,size=(5,5))
print(array)



rmean=np.mean(array,axis=1)
print(rmean)

cmean=np.mean(array,axis=0)
print(cmean)



replace=np.where(array%2==0,-1,array)
print(replace)


csrt=np.sort(array,axis=0)
print(csrt)

rsrt=np.sort(array,axis=1)
print(rsrt)


rsum=np.sum(array,axis=1)
print(rsum)


csum=np.sum(array,axis=0)
print(csum)



cnt_col=np.sum(np.where(replace<0,1,0),axis=0)
print(cnt_col)

[[41 10 62 16 63]
 [75 73 18 73 87]
 [ 8 20 61 20 26]
 [33 34 24 61 86]
 [54 53 13 82 86]]
[38.4 65.2 27.  47.6 57.6]
[42.2 38.  35.6 50.4 69.6]
[[41 -1 -1 -1 63]
 [75 73 -1 73 87]
 [-1 -1 61 -1 -1]
 [33 -1 -1 61 -1]
 [-1 53 13 -1 -1]]
[[ 8 10 13 16 26]
 [33 20 18 20 63]
 [41 34 24 61 86]
 [54 53 61 73 86]
 [75 73 62 82 87]]
[[10 16 41 62 63]
 [18 73 73 75 87]
 [ 8 20 20 26 61]
 [24 33 34 61 86]
 [13 53 54 82 86]]
[192 326 135 238 288]
[211 190 178 252 348]
[2 3 3 3 3]


Ques--2

In [41]:
import numpy as np
stock_level=np.random.randint(1,91,size=(5,5))

demand=np.random.randint(1,91,size=(5,5))


remaning_stock=stock_level-demand
print(remaning_stock)
print("\n")


out_stock=np.where(remaning_stock<0,0,remaning_stock)
print(out_stock)
print("\n")



zeroshortage=np.sum(np.where(out_stock==0,1,0),axis=1)
print(zeroshortage)
print("\n")


totalshortage=np.sum(np.where(remaning_stock<0,remaning_stock,0),axis=1)
print(totalshortage)
print("\n")


rsort=np.sort(remaning_stock,axis=1)
print(rsort)






[[  9 -31 -79  25  47]
 [-58  11  36  61   7]
 [ 47  51  20  -2 -72]
 [-57  79 -81  50 -62]
 [ 24 -17  54 -32 -63]]


[[ 9  0  0 25 47]
 [ 0 11 36 61  7]
 [47 51 20  0  0]
 [ 0 79  0 50  0]
 [24  0 54  0  0]]


[2 1 2 3 3]


[-110  -58  -74 -200 -112]


[[-79 -31   9  25  47]
 [-58   7  11  36  61]
 [-72  -2  20  47  51]
 [-81 -62 -57  50  79]
 [-63 -32 -17  24  54]]
